### PR TITLE
Add implementation of likely subtags

### LINKED ISSUE #9: Likely subtags
I need "likely subtags" for script-aware fallback. ICU has [an implementation](http://icu-project.org/apiref/icu4c64rc/classicu_1_1Locale.html#a974d212572d7fc61a0579f820100a8f6).

I actually have this pretty well implemented. The question is whether it belongs in fluent-locale-rs or whether it should be in skribo. I estimate that it's in the ballpark of 50k of code and data; I could probably get it down a little.

Also, I haven't implemented the deprecated subtags (for example, the conversion of "sh" to "sr_Latn". I suspect I won't miss them for text rendering, but other applications might want them (for example, so that hyphenation can handle "no-NO"). If I submitted a PR, would you want these?

A "no" answer is fine - it'll just live in skribo.

### LINKED ISSUE #10: Incorrect existing likely subtags
This issue is related to #9, and I want to try to figure it out while making a PR.

First, there are two locales for which the existing logic is simply wrong. "cs" results in "cs-CS", while the region should be CZ, and similarly for "sr", should be "sr-Cyrl-RS" rather than "sr-Cyrl-SR".

A deeper issue is that this logic is very inconsistent whether it adds a script or not. It feels to me like the right thing to do is add a script. However, this makes three of the negotiate tests fail. I feel that if any downstream logic is dependent on the script not being present (as is the case now), it is pretty fragile. However, fixing this feels like a bit of a yak-shave, so I'm filing this issue asking for advice.

I'll also prepare a minimally invasive PR for likely subtags.

### PR DESCRIPTION
**Pull request by raphlinus**
Fixes #9 and partly fixes #10 but has test failures when the
`likely-subtags` feature is enabled, as discussed in #10.

This implementation follows the Unicode recommendataions fairly
closely but does not implement deprecated or grandfathered mappings.

### CODE REVIEW

**Comment by zbraniecki** [comment]
Great, thank you!

I'm going to review it next week - is that ok?

**Comment by raphlinus** [comment]
Yes, it's fine, I can continue with this locally patched. More important to get this right than to get it in quickly :)

Another point while I'm at it. It's possible to replace the binary search lookups with minimal perfect hashes as in https://github.com/unicode-rs/unicode-normalization/pull/37 . I have a feeling the speed improvement is not worth the extra maintenance complexity, but let me know.

**Comment by zbraniecki** [comment]
@raphlinus - can we move this to `unic-langid` crate?

**Comment by raphlinus** [comment]
Same as the other PR, sure.

**Comment by zbraniecki** [comment]
I started working on that in unic-locale - https://github.com/zbraniecki/unic-locale/pull/15/files

For now the implementation is very naive and slow, but should be fairly complete.

**Pull request closed without merging**
