### PR TITLE
Factor out the testing strategy

### PR DESCRIPTION
**Pull request by zbraniecki**
@emilio - I tried to factor it out as per your phabricator review request, but I can't avoid performance penalty from this.

```
     Running target/release/deps/negotiate-ac68a6f1cbdbed1f
Gnuplot not found, disabling plotting
negotiate               time:   [2.5452 us 2.5697 us 2.6008 us]
                        change: [+12.053% +16.636% +21.440%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) high mild
  4 (4.00%) high severe
```

I like the readability improvement, but 16% perf penalty seems quite high. Can you verify that I'm not doing anything wrong?
If it looks good, what do you think?

### CODE REVIEW

**Comment by emilio** [comment]
So to be fair I was quite surprised it had a measurable impact on perf, but indeed it does. I think we're hitting some differences in how LLVM optimizes the function...

It may be worth a bug in rustc after a bit more testing. But meanwhile, why not having both? #19 accomplishes the code reuse with a macro rather than an inline function, and I think it's better than the status quo, but it's your call ultimately :)

**Comment by emilio** [comment]
Interestingly, both `-C opt-level=3` and `-Z mutable-noalias=yes` don't move a dent...

**Comment by zbraniecki** [comment]
> It may be worth a bug in rustc after a bit more testing.

I never filed a bug in rustc. If you think it's worth it, can you guide me through the process? Do I need to prepare some minimized testcase or just point at a revision of this repo and the PR?

**Comment by emilio** [comment]
> I never filed a bug in rustc. If you think it's worth it, can you guide me through the process? Do I need to prepare some minimized testcase or just point at a revision of this repo and the PR?

I think it's worth it, though maybe it's an upstream llvm bug.

The TLDR is filing an issue on https://github.com/rust-lang/rust/issues/new with steps to reproduce, in this case probably giving concrete links to revisions of this repo (with and without patch), and noting how performance clearly regressed, even though behavior is the same and assembly should be mostly identical.

Also noting that various optimization tweaks that I thought could have helped (`-C opt-level=3` and `-Z mutable-noalias=yes`) do not actually help.

Ideally something more reduced than this crate would be amazing of course, but I don't know how to do that so assistance from the Rust folks if they need it would be useful...

To be clear, I don't have extremely high hopes of somebody having the cycles to debug it and fix it right away, but filing it is relatively low effort and this looks quite actionable, if probably hard to figure out the root cause.

**Pull request closed without merging**
